### ISSUE TITLE
[FE] : navigation

### ISSUE THREAD

**Issue by modernToujours** [hong-yura/WorkForUs-Project#8]
## 🔔 요구 사항
전체 페이지에 사용할 navigation을 생성 및 favicon 추가

## ✅ 수행 작업
- [x] navbar module 추가
- [x] favicon 추가

## 🚧 참고 사항
- submenu 변경 필요

**Comment by hong-yura** [comment]
submenu는 추후에 각자 변경해주세요~
@jaeeukim @boseuly @GYUYOEN
